services:
  # Backend API
  backend:
    build:
      context: ./crypto-tracker-backend
      dockerfile: Dockerfile
    container_name: crypto-tracker-backend
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=JEKIEEoW_uMfO97AQbDGhaGSMK0LnLxBcN7DVWzpFOA
      - JWT_SECRET_KEY=xT9EeosDjKCpOyf8eaNPJJie8LYGLr3g5Ht-99_Y2ew
      - CORS_ORIGINS=http://localhost:3000
    ports:
      - "5002:5000"
    networks:
      - crypto-network
    volumes:
      - ./crypto-tracker-backend/instance:/app/instance
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./crypto-tracker-frontend
      dockerfile: Dockerfile
    container_name: crypto-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - crypto-network
    restart: unless-stopped


networks:
  crypto-network:
    driver: bridge