services:
  # Backend API Service
  - type: web
    name: crypto-tracker-backend
    runtime: docker
    dockerfilePath: ./crypto-tracker-backend/Dockerfile
    dockerContext: ./crypto-tracker-backend
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY  
        generateValue: true
      - key: CORS_ORIGINS
        value: https://crypto-tracker-frontend.onrender.com,http://localhost:3000
      - key: PORT
        value: 5000
    disk:
      name: crypto-data
      mountPath: /app/instance
      sizeGB: 1

  # Frontend Web Service  
  - type: web
    name: crypto-tracker-frontend
    runtime: docker
    dockerfilePath: ./crypto-tracker-frontend/Dockerfile
    dockerContext: ./crypto-tracker-frontend
    region: oregon
    plan: free
    branch: main
    buildCommand: ""
    dockerBuildArgs:
      - key: VITE_API_URL
        value: https://crypto-tracker-backend.onrender.com

# Optional: Background Jobs for price updates
  # - type: worker
  #   name: price-updater
  #   runtime: docker
  #   dockerfilePath: ./crypto-tracker-backend/Dockerfile
  #   dockerContext: ./crypto-tracker-backend
  #   region: oregon
  #   plan: free
  #   branch: main
  #   startCommand: python scripts/price_updater.py
  #   envVars:
  #     - fromService:
  #         type: web
  #         name: crypto-tracker-backend
  #         envVarKey: DATABASE_URL

databases:
  # Optional: PostgreSQL database (if you want to upgrade from SQLite)
  # - name: crypto-tracker-db
  #   databaseName: crypto_tracker
  #   user: crypto_user
  #   region: oregon
  #   plan: free