services:
  # Backend API Service
  - type: web
    name: crypto-tracker-backend
    runtime: docker
    dockerfilePath: ./crypto-tracker-backend/Dockerfile
    dockerContext: ./crypto-tracker-backend
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY  
        generateValue: true
      - key: CORS_ORIGINS
        value: https://crypto-tracker-frontend.onrender.com,http://localhost:3000
      - key: PORT
        value: 5000
    disk:
      name: crypto-data
      mountPath: /app/instance
      sizeGB: 1

  # Frontend Web Service  
  - type: web
    name: crypto-tracker-frontend
    runtime: docker
    dockerfilePath: ./crypto-tracker-frontend/Dockerfile
    dockerContext: ./crypto-tracker-frontend
    region: oregon
    plan: free
    branch: main
    buildCommand: ""
    envVars:
      - key: VITE_API_URL
        value: https://crypto-tracker-backend.onrender.com