services:
  - type: web
    name: crypto-tracker-frontend
    runtime: static
    rootDir: crypto-tracker-frontend
    buildCommand: npm ci --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    
  - type: web
    name: crypto-tracker-backend  
    runtime: python
    rootDir: crypto-tracker-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
          
databases:
  - name: crypto-db
    plan: starter