# ===============================================
# ALERTMANAGER CONFIGURATION
# ===============================================
# Alert routing, grouping, and notification configuration
# for crypto tracker monitoring system.

global:
  # SMTP configuration for email alerts
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${ALERT_FROM_EMAIL}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true
  
  # Default notification settings
  resolve_timeout: 5m

# -----------------------------------------------
# NOTIFICATION TEMPLATES
# -----------------------------------------------
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# -----------------------------------------------
# ALERT ROUTING
# -----------------------------------------------
route:
  # Default route settings
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s          # Wait before sending notification for new group
  group_interval: 5m       # Wait before sending notification for new alerts in group
  repeat_interval: 4h      # Wait before resending notification
  receiver: 'default'      # Default receiver
  
  # Routing rules (processed in order)
  routes:
    # -----------------------------------------------
    # CRITICAL ALERTS - IMMEDIATE NOTIFICATION
    # -----------------------------------------------
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 30m
      routes:
        # Database issues - notify DB team immediately
        - match:
            service: postgresql
          receiver: 'database-team'
          group_wait: 0s
        
        # Application down - notify platform team
        - match_re:
            alertname: '.*Down$'
          receiver: 'platform-team'
          group_wait: 0s

    # -----------------------------------------------
    # WARNING ALERTS - BUSINESS HOURS ONLY
    # -----------------------------------------------
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 2m
      group_interval: 10m
      repeat_interval: 2h
      # Only send during business hours (9 AM - 6 PM UTC, Mon-Fri)
      active_time_intervals:
        - 'business-hours'

    # -----------------------------------------------
    # SECURITY ALERTS - SECURITY TEAM
    # -----------------------------------------------
    - match:
        team: security
      receiver: 'security-team'
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 1h

    # -----------------------------------------------
    # BUSINESS METRICS - PRODUCT TEAM
    # -----------------------------------------------
    - match:
        team: product
      receiver: 'product-team'
      group_wait: 10m
      group_interval: 1h
      repeat_interval: 24h

    # -----------------------------------------------
    # INFRASTRUCTURE ALERTS
    # -----------------------------------------------
    - match:
        team: infrastructure
      receiver: 'infrastructure-team'
      group_wait: 5m
      group_interval: 15m
      repeat_interval: 4h

# -----------------------------------------------
# TIME INTERVALS
# -----------------------------------------------
time_intervals:
  - name: 'business-hours'
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '18:00'
        weekdays: ['monday:friday']
        location: 'UTC'

  - name: 'weekend'
    time_intervals:
      - weekdays: ['saturday', 'sunday']

# -----------------------------------------------
# NOTIFICATION RECEIVERS
# -----------------------------------------------
receivers:
  # -----------------------------------------------
  # DEFAULT RECEIVER
  # -----------------------------------------------
  - name: 'default'
    email_configs:
      - to: '${DEFAULT_ALERT_EMAIL}'
        subject: '[Crypto Tracker] {{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ if .Annotations.runbook_url }}**Runbook:** {{ .Annotations.runbook_url }}{{ end }}
          {{ if .Annotations.dashboard_url }}**Dashboard:** {{ .Annotations.dashboard_url }}{{ end }}
          {{ end }}

  # -----------------------------------------------
  # CRITICAL ALERTS - MULTIPLE CHANNELS
  # -----------------------------------------------
  - name: 'critical-alerts'
    # Email notification
    email_configs:
      - to: '${CRITICAL_ALERT_EMAIL}'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} - Crypto Tracker'
        body: |
          🚨 **CRITICAL ALERT** 🚨
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Environment:** {{ .Labels.environment }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          {{ if .Annotations.runbook_url }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}
          
          Please investigate immediately!
    
    # Slack notification
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '${SLACK_CRITICAL_CHANNEL}'
        title: '🚨 Critical Alert - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Severity:* {{ .Labels.severity }}
          *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ if .Annotations.dashboard_url }}
          <{{ .Annotations.dashboard_url }}|View Dashboard>
          {{ end }}
          {{ end }}
        send_resolved: true
    
    # PagerDuty integration (if configured)
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .GroupLabels.alertname }} - {{ .CommonAnnotations.summary }}'
        details:
          severity: '{{ .CommonLabels.severity }}'
          service: '{{ .CommonLabels.service }}'
          environment: '{{ .CommonLabels.environment }}'

  # -----------------------------------------------
  # WARNING ALERTS - BUSINESS HOURS ONLY
  # -----------------------------------------------
  - name: 'warning-alerts'
    email_configs:
      - to: '${WARNING_ALERT_EMAIL}'
        subject: '⚠️ WARNING: {{ .GroupLabels.alertname }} - Crypto Tracker'
        body: |
          ⚠️ **WARNING ALERT** ⚠️
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
          
          Please investigate when convenient during business hours.
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '${SLACK_WARNING_CHANNEL}'
        title: '⚠️ Warning - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Service:* {{ .Labels.service }}
          {{ end }}
        send_resolved: true

  # -----------------------------------------------
  # TEAM-SPECIFIC RECEIVERS
  # -----------------------------------------------
  
  - name: 'platform-team'
    email_configs:
      - to: '${PLATFORM_TEAM_EMAIL}'
        subject: '[Platform] {{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#platform-alerts'
        title: 'Platform Alert - {{ .GroupLabels.alertname }}'

  - name: 'database-team'
    email_configs:
      - to: '${DATABASE_TEAM_EMAIL}'
        subject: '[Database] {{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#database-alerts'
        title: 'Database Alert - {{ .GroupLabels.alertname }}'

  - name: 'security-team'
    email_configs:
      - to: '${SECURITY_TEAM_EMAIL}'
        subject: '🔒 [Security] {{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: '🔒 Security Alert - {{ .GroupLabels.alertname }}'

  - name: 'product-team'
    email_configs:
      - to: '${PRODUCT_TEAM_EMAIL}'
        subject: '[Product] {{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#product-metrics'
        title: 'Product Metrics Alert - {{ .GroupLabels.alertname }}'

  - name: 'infrastructure-team'
    email_configs:
      - to: '${INFRASTRUCTURE_TEAM_EMAIL}'
        subject: '[Infrastructure] {{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#infrastructure-alerts'
        title: 'Infrastructure Alert - {{ .GroupLabels.alertname }}'

# -----------------------------------------------
# INHIBITION RULES
# -----------------------------------------------
inhibit_rules:
  # If service is down, inhibit all other alerts for that service
  - source_matchers:
      - alertname =~ ".*Down$"
    target_matchers:
      - alertname !~ ".*Down$"
    equal: ['service']

  # If high error rate, inhibit individual error alerts
  - source_matchers:
      - alertname = "HighErrorRate"
    target_matchers:
      - alertname =~ ".*Error.*"
    equal: ['service']

  # If system is under high load, inhibit performance alerts
  - source_matchers:
      - alertname = "HighLoadAverage"
    target_matchers:
      - alertname =~ ".*(Slow|Performance).*"
    equal: ['instance']

# -----------------------------------------------
# MUTE TIME INTERVALS
# -----------------------------------------------
mute_time_intervals:
  # Mute non-critical alerts during maintenance windows
  - name: 'maintenance-window'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['sunday']
        location: 'UTC'