# ===============================================
# PROMETHEUS CONFIGURATION
# ===============================================
# Monitoring configuration for crypto tracker application.
# Collects metrics from application, infrastructure, and external services.

global:
  scrape_interval: 30s      # Default scrape interval
  evaluation_interval: 30s  # Rule evaluation interval
  scrape_timeout: 10s       # Timeout for scrapes
  
  # External labels for alertmanager
  external_labels:
    monitor: 'crypto-tracker'
    environment: 'production'
    region: 'us-east-1'

# -----------------------------------------------
# RULE FILES
# -----------------------------------------------
rule_files:
  - "rules/*.yml"
  - "alerts/*.yml"

# -----------------------------------------------
# ALERTING CONFIGURATION
# -----------------------------------------------
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# -----------------------------------------------
# SCRAPE CONFIGURATIONS
# -----------------------------------------------
scrape_configs:

  # -----------------------------------------------
  # PROMETHEUS SELF-MONITORING
  # -----------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # -----------------------------------------------
  # CRYPTO TRACKER BACKEND
  # -----------------------------------------------
  - job_name: 'crypto-tracker-backend'
    static_configs:
      - targets: ['backend:5001']
    
    # Metrics endpoint configuration
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    
    # Additional labels
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'crypto-backend'
      - target_label: service
        replacement: 'crypto-tracker-backend'
      - target_label: environment
        replacement: 'production'
    
    # HTTP configuration
    scheme: http
    
    # Health check configuration
    honor_labels: false
    honor_timestamps: true

  # -----------------------------------------------
  # CRYPTO TRACKER FRONTEND (NGINX)
  # -----------------------------------------------
  - job_name: 'crypto-tracker-frontend'
    static_configs:
      - targets: ['frontend:3000']
    
    metrics_path: /nginx_status
    scrape_interval: 30s
    
    relabel_configs:
      - target_label: service
        replacement: 'crypto-tracker-frontend'
      - target_label: environment
        replacement: 'production'

  # -----------------------------------------------
  # DATABASE MONITORING
  # -----------------------------------------------
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    
    scrape_interval: 30s
    
    relabel_configs:
      - target_label: service
        replacement: 'postgresql'
      - target_label: database
        replacement: 'crypto_tracker'

  # -----------------------------------------------
  # REDIS MONITORING
  # -----------------------------------------------
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    
    scrape_interval: 30s
    
    relabel_configs:
      - target_label: service
        replacement: 'redis'
      - target_label: instance
        replacement: 'crypto-tracker-cache'

  # -----------------------------------------------
  # CONTAINER MONITORING (CADVISOR)
  # -----------------------------------------------
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    
    scrape_interval: 30s
    metrics_path: /metrics
    
    relabel_configs:
      - target_label: service
        replacement: 'container-metrics'

  # -----------------------------------------------
  # NODE EXPORTER (SYSTEM METRICS)
  # -----------------------------------------------
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
    scrape_interval: 30s
    
    relabel_configs:
      - target_label: service
        replacement: 'system-metrics'

  # -----------------------------------------------
  # BLACKBOX EXPORTER (UPTIME MONITORING)
  # -----------------------------------------------
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # HTTP 200 response check
    
    static_configs:
      - targets:
        - http://frontend:3000/health    # Frontend health
        - http://backend:5001/api/v1/health  # Backend health
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # -----------------------------------------------
  # EXTERNAL API MONITORING
  # -----------------------------------------------
  - job_name: 'external-apis'
    metrics_path: /probe
    params:
      module: [http_2xx]
    
    static_configs:
      - targets:
        - https://api.coingecko.com/api/v3/ping
        - https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: service
        replacement: 'external-api'

  # -----------------------------------------------
  # APPLICATION METRICS (CUSTOM)
  # -----------------------------------------------
  - job_name: 'crypto-tracker-custom-metrics'
    static_configs:
      - targets: ['backend:5001']
    
    metrics_path: /api/v1/metrics
    scrape_interval: 60s  # Less frequent for business metrics
    
    relabel_configs:
      - target_label: service
        replacement: 'business-metrics'
      - target_label: application
        replacement: 'crypto-tracker'

# -----------------------------------------------
# REMOTE STORAGE (OPTIONAL)
# -----------------------------------------------
# remote_write:
#   - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
#     basic_auth:
#       username: "username"
#       password: "password"

# -----------------------------------------------
# STORAGE CONFIGURATION
# -----------------------------------------------
storage:
  tsdb:
    # Retention policy
    retention.time: '30d'        # Keep data for 30 days
    retention.size: '10GB'       # Maximum storage size
    
    # Compression
    wal-compression: true
    
    # Performance tuning
    max-block-duration: '2h'     # Maximum block duration
    min-block-duration: '2h'     # Minimum block duration

# -----------------------------------------------
# FEATURE FLAGS
# -----------------------------------------------
feature_flags:
  # Enable new features (Prometheus 2.x)
  enable_feature:
    - "expand-external-labels"
    - "memory-snapshot-on-shutdown"
    - "promql-at-modifier"
    - "promql-negative-offset"